apiVersion: batch/v1
kind: Job
metadata:
  name: load-tester
  namespace: development
spec:
  parallelism: 10
  template:
    spec:
      containers:
      - name: hey
        image: williamyeh/hey
        args: ["-z", "15m", "-c", "500", "http://tetris-service"]
      restartPolicy: Never
  backoffLimit: 0
